[package]
name = "iterators_extended"
version = "0.1.0"
edition = "2021"
license = "MIT"
readme = "README.md"
repository = "https://github.com/adamthedash/iterators"
authors = ["Adam Power <adamthedash2@gmail.com>"]

[dependencies]
